# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e6aec279b0d44da165eff9df5caaa8f6386f5bdc80841891eb623dfc7387be5deca1ba578c02d31f95ce5e0e04c7a9682693519a36231c995f2e9eb5e169e8c

test:
  secret_key_base: ac8ce3b8f2805f4e9f845cc8636ad9efe540c5ed5375db0f8be2f9287183de2b03be6cc154cdf8cc7eb6181523489c4a08ccf4edabb749ae94dafc08c1c59199

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
